# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
title: International Autumn School
#email: specathehn@gmail.com
#url: https://CP2Kautumnschool.github.io/
url: https://SPECATgroup.github.io/CP2Kautumnschool/
description: >- # this means to ignore newlines until "baseurl:"
 CP2K-Newton-X-WaveMixings
# This 3-day autumn school focuses on mixed quantum-classical molecular dynamics using CP2K, Newton-X and WaveMixings on High-Performance Computing (HPC) cluster systems.
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  SPECATgroup


#![Alt text]({{ "/images/CP2K_Newton_X_Wavemixings_Logo.png" | relative_url }})
# Build settings
theme: minima
#plugins:
#  - jekyll-feed

#collections:
#  schedule:
#    output: true
#    permalink: /:collection/:name
#  venue:
#    output: false
#  registration:
#    output: false
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
